# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 505cacf1b75a32f808aacbb2aa27f3b32243a6461739231aac0f75192566118b8b153e47b41fc99023b6303fbf4757f7c658f365c411e70628e44bc8b01c4d37

test:
  secret_key_base: 5ae7c78a10cfce0113c56d9ba11e3345ae6797aa4ffa9f03b0df7c281380d376319f82f9c024c6fa87394bd5eba73f273287bacb20fe0fce0422015900e02b8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
